name: 'AKS Deployment'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  aks:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP }}
      LOCATION: ${{ vars.LOCATION }}
      DNS_PREFIX: ${{ vars.AKS_NAME }}
      CLUSTER_NAME: ${{ vars.AKS_NAME }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: terraform/aks
      run: terraform init
           
    - name: Terraform Format
      working-directory: terraform/aks
      run: terraform fmt

    - name: Terraform Plan
      working-directory: terraform/aks
      run: terraform plan
    
    - name: Terraform Apply
      working-directory: terraform/aks
      run: terraform apply -auto-approve